/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.farmatech.metrofarm.utils;

import com.co.farmatech.metrofarm.dto.PageData;
import javax.swing.JButton;

/**
 *
 * @author bestrada
 */
public class PanelPaginador extends javax.swing.JPanel {

    PageData pageData;

    /**
     * Creates new form PanelPaginador
     */
    public PanelPaginador() {
        initComponents();
        pageData = new PageData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackward = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnForward = new javax.swing.JButton();
        txtpagina = new javax.swing.JTextField();

        setBackground(getBackground());

        btnBackward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/farmatech/metrofarm/resources/imagenes/backward.png"))); // NOI18N
        btnBackward.setToolTipText("Primero");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/farmatech/metrofarm/resources/imagenes/back.png"))); // NOI18N
        btnBack.setToolTipText("Regresar");

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/farmatech/metrofarm/resources/imagenes/next.png"))); // NOI18N
        btnNext.setToolTipText("Siguiente");

        btnForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/farmatech/metrofarm/resources/imagenes/forward.png"))); // NOI18N
        btnForward.setToolTipText("Último");

        txtpagina.setEditable(false);
        txtpagina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpagina.setText("0");
        txtpagina.setToolTipText("número de página");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBackward)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpagina, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForward)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnNext)
                    .addComponent(btnForward)
                    .addComponent(btnBackward))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtpagina)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnNext;
    private javax.swing.JTextField txtpagina;
    // End of variables declaration//GEN-END:variables

    //metodos
    
    public void setPagText(String text) {
        this.txtpagina.setText(text);
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnBackward() {
        return btnBackward;
    }

    public JButton getBtnForward() {
        return btnForward;
    }

    public JButton getBtnNext() {
        return btnNext;
    }

    public PageData getPageData() {
        return pageData;
    }
    
    public void enablePageButtons(){
        this.btnBackward.setEnabled(true);
        this.btnBack.setEnabled(true);
        this.btnNext.setEnabled(true);
        this.btnForward.setEnabled(true);
    }
    
    
    
    
}
